// redux/tenantActionTypes.js
export const FETCH_TENANTS_SUCCESS = 'FETCH_TENANTS_SUCCESS';
export const FETCH_TENANTS_FAILURE = 'FETCH_TENANTS_FAILURE';

export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';

export const FETCH_UTILITY_SUCCESS = 'FETCH_UTILITY_SUCCESS';
export const FETCH_UTILITY_FAILURE = 'FETCH_UTILITY_FAILURE';

export const FETCH_UTILITYARRAYDATA_SUCCESS = 'FETCH_UTILITYARRAYDATA_SUCCESS';
export const FETCH_UTILITYARRAYDATA_FAILURE = 'FETCH_UTILITYARRAYDATA_FAILURE';
